### ISSUE TITLE
Problem with Map Markers on 1.19.2 version

### ISSUE THREAD

**Issue by ImtheFBM** [MehVahdJukaar/mapatlases-neoforge#10]
![2023-09-09_21 12 05](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/144556562/2d5debb3-2173-4845-87a0-882fd648f52b)

When zoomed out every marker except for banners get smaller. Banners keep the same size they had before.

![2023-09-09_21 12 06](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/144556562/8c020bbf-5535-4430-ae45-a4946728b863)

Version Used: Map Atlases-forge-1.19.2-3.0.1.jar

**Comment by MehVahdJukaar** [comment]
This has been fixed in newer moonlight versions with direct compatibility with the atlas zoom feature. Once I'm done overhauling the mod I'll backport to 1.19

**Comment by MehVahdJukaar** [comment]
Also technically it's the banners that get bigger xD
