### ISSUE TITLE
No pin works in 1.19.2 (lastest version)

### ISSUE THREAD

**Issue by Pedritoc25** [MehVahdJukaar/mapatlases-neoforge#100]
Mod archive: map_atlases-1.19-6.0.3.jar

There is any marker.
I got all the compat mods that the cursefurge say it works without xaeros minimap

![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/96841952/02cd23dd-06d0-4fe8-b179-306584bb0e56)

**Comment by MehVahdJukaar** [comment]
Any pin works means that they all work? Did you mean no pin works? 1.19 does not have pins. I do on the wiki is only relevant I to the latest version

**Comment by WillBMorra** [comment]
Sorry, miswrote. Got it, is there any plans or it's only for latest versions?

**Comment by MehVahdJukaar** [comment]
no plans to backport this stuff. I alreayd backported almost all the features for this mod back to 1.19 3 separate times 3 separate backports as internal changes were just too great. I dont want to do any more of that as that system is evne bigger

**Comment by WillBMorra** [comment]
Make sense. Ty for the answer

**Comment by Pedritoc25** [comment]
> Any pin works means that they all work? Did you mean no pin works? 1.19 does not have pins. I do on the wiki is only relevant I to the latest version

Hello. I meant "No pin works", sorry for the bad english. And thanks for the
clarification.

**Comment by Pedritoc25** [comment]
"1.19 does not have pins" -MehVahdJukaar
