### ISSUE TITLE
Fabric 1.20.1 - Anchors don't work

### ISSUE THREAD

**Issue by Partonetrain** [MehVahdJukaar/mapatlases-neoforge#105]
The anchor config option being anything besides UPPER_LEFT makes the minimap disappear. All other position-related configs are default.
Using map_atlases-1.20-6.0.2
supplementaries 1.20-2.8.1
moonlightlib 1.20.2.10.9

**Comment by MehVahdJukaar** [comment]
The do work tho it's likely they are not set up properly so it renders too far to the right

**Comment by Partonetrain** [comment]
Do the offsets need to be negative?

**Comment by MehVahdJukaar** [comment]
yeah if you mess with those other offset the map will eventually go back where you want. acnhors are just some additions to the offset numbers

**Comment by Partonetrain** [comment]
After much trial and error, I found good values for LOWER_LEFT. Posting them here for others:
![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/19861808/4ad68fe6-91f6-4a31-82b2-fe32ab6cc705)
