### ISSUE TITLE
Crashing in game when trying to create Map Atlas book. Says supplementaries issue but idk

### ISSUE THREAD

**Issue by ThatWasMyName** [MehVahdJukaar/mapatlases-neoforge#110]
Hi, sorry playing with a ton of mods. I load into game alright and everything plays well. The mod affects a normal map as it should but when I go to create a Map Atlas book it just crashes. I crash as soon as I put a slime, book, and filled map into a crafting bench. 
(If the file upload states anywhere that it crashed on an all the mod 9 modded world ignore that. I gutted the modpack and revamped everything for my own custom modpack)

Forge version: 47.2.16
Game Version: 1.20.1
Using Map Atlas forge version: map_atlases-1.20-6.0.3.jar
Crash pop up:
The game crashed whilst rendering screen
Error: java.lang.NoClassDefFoundError: net/mehvahdjukaar/supplementaries/common/items/AntiqueInkItem
Crash log:
[crash-2024-03-11_20.11.23-client.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/14565638/crash-2024-03-11_20.11.23-client.txt)

This is my first time reporting an issue. My apologies if I missed anything I should have added.

**Comment by MehVahdJukaar** [comment]
your supplementaries is outated

**Comment by ThatWasMyName** [comment]
Ah, my apologies. Sorry for my mistake. Have a nice day.
