### ISSUE TITLE
No minimap rendering at all [1.20.1 Fabric]

### ISSUE THREAD

**Issue by Boingboingsplat** [MehVahdJukaar/mapatlases-neoforge#115]
After updating my version of the mod from the last version that's available on Modrinth to the newest release on Curseforge I simply don't have any minimap rendering whatsoever, no matter where the atlas is in my inventory.

Minecraft 1.20.1
Fabric Loader 0.15.7
Fabric API 0.92.0+1.20.1
Map Atlases 1.20-6.0.4-fabric

**Comment by MehVahdJukaar** [comment]
reset the config file

**Comment by Boingboingsplat** [comment]
Issue persists even after deleting the config file and letting it regenerate.

**Comment by MehVahdJukaar** [comment]
hm. what happens if you change gui size or change the minimap anchoring config?

**Comment by Boingboingsplat** [comment]
I've tried tinkering with GUI size and the anchoring settings but I've yet to find any combination of settings to make anything appear.

**Comment by Boingboingsplat** [comment]
Version 6.0.5 fixes the issue for me, so I suppose it was related to #113. I'll close this issue.
