### ISSUE TITLE
[Forge 1.19.2 6.0.4] Map Atlas 

### ISSUE THREAD

**Issue by murilorodelli** [MehVahdJukaar/mapatlases-neoforge#129]
![2024-05-10_17 14 01](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/2029666/d700295f-21ca-4f8d-a42a-118a7f65bf5a)

Even with supplementaries and moonnlightlib, pin management doesn't work

**Comment by MehVahdJukaar** [comment]
You are using an old discontinued version

**Comment by elifian** [comment]
But there is no mod version higher than 6.0.4 for 1.19.2...

**Comment by BitBork** [comment]
Same issue here, ver 6.0.4 on 1.19.2, any fix?

**Comment by MehVahdJukaar** [comment]
il close because its not an issue. The old version is simply old and doesnt have all new features
