### ISSUE TITLE
rotate_with_player = false still has cardinal direction markers rotating

### ISSUE THREAD

**Issue by rckymtnrfc** [MehVahdJukaar/mapatlases-neoforge#13]
It seems with rotate_with_player = false the cardinal direction marks are still rotating with the player.  

Forge 47.1.47
Supp 2.6.1
Map Atlas 5.0.3
Moonlight 2.8.25

And just out of curiosity.  Any thoughts on making the world map size independent from the GUI scale?  When my GUI set to 3, I have a lot of wasted space around the map.

**Comment by MehVahdJukaar** [comment]
Well true but to be fair those loose their meaning when rotate player is false as north is always up

**Comment by MehVahdJukaar** [comment]
There are configs to force scale the gui

**Comment by rckymtnrfc** [comment]
I'll check for the GUI scale, setting I must have missed it.  Thanks.

As a follow up.  The small white arrow that represents the player seemed to get stuck on one location and wasn't rotating to face the direction of the player.  Maybe I'm wrong but shouldn't that stay locked to the center of the minimap?

**Comment by MehVahdJukaar** [comment]
Can you show a picture? Does that happen with rotate with player or not? Then option is on a bigger static sprite is actually always drawn perfectly on the center

**Comment by rckymtnrfc** [comment]
Yeah, I'll get a shot of it when I see the issue again.

**Comment by MehVahdJukaar** [comment]
fixed
