### ISSUE TITLE
[request] Toggle marker text display

### ISSUE THREAD

**Issue by TwelveYO21** [MehVahdJukaar/mapatlases-neoforge#130]
I would like to be able to change it in the settings.
If possible, it would be great if the mini-map and world map can be set separately.

**Comment by MehVahdJukaar** [comment]
Which markers?

**Comment by TwelveYO21** [comment]
Here it is. 
Because displaying text on a narrow mini-map would obscure the terrain

![2024-05-19_13 20 59](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/58351699/ea7d5c9e-89ec-402d-9b72-f7ab41dc5a3f)

**Comment by MehVahdJukaar** [comment]
Why not using the config for text scale? I think there's one for the minimap

**Comment by TwelveYO21** [comment]
Ah, I see!
I'm currently down to 0.5, I just need to set this to 0.
That was a blind spot, thanks.

**Comment by TwelveYO21** [comment]
Oops, I just looked and the marker text scale setting is shared by both the minimap and the world map.
There are no individual settings.

**Comment by TwelveYO21** [comment]
It can now be set separately!
Thanks very much for the quick response!
