### ISSUE TITLE
No crafting recipes for Atlases (5.1.0)

### ISSUE THREAD

**Issue by Typhonidite** [MehVahdJukaar/mapatlases-neoforge#14]
Uh, self-explanatory. 5.1.0.
Tried /recipe give @s map_atlases:craft_atlas myself just to be sure, but attempting that said "no more recipes were learned."
On the contrary, attempting /recipe take resulted in "no recipes could be forgotten." So it's... _there_, but also _not_ there.

**Comment by MehVahdJukaar** [comment]
Forget about the command. Can you craft the atlas or not? Filled map + book + slimeball

**Comment by Typhonidite** [comment]
Ah, yeah, I guess that would be a helpful tidbit of info to include. Yes, all recipes work fine, just don't show in the recipe book.

**Comment by MehVahdJukaar** [comment]
They are special recipes just like vanilla banner duplicate or map clone. Those don't appear there either. That's why I have jei integration

**Comment by MehVahdJukaar** [comment]
And ita not up to me how the recipe book works it's very supid and only shows shaped or shapeless crafting. Nobody should use it when playing modded

**Comment by Typhonidite** [comment]
> They are special recipes just like vanilla banner duplicate or map clone. Those don't appear there either. That's why I have jei integration

Ah, alright, I had thought that might be the case. Thank you for clearing it up.
