### ISSUE TITLE
Crash after opening up an atlas/having an atlas in your inventory

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/mapatlases-neoforge#15]
Using: Forge 1.19.2, version 5.0.1 and Moonlight version 2.2.44. 

Crash report: https://gist.github.com/thelegitdolt/a198260d6f374e0e895114947d6bfbe7
Latest.log: https://gist.github.com/thelegitdolt/d6b8c62d02562cd033900ab8114f89e0

**Comment by MehVahdJukaar** [comment]
hm i updated some stuff. does it still happen?

**Comment by HUYBUSSIN** [comment]
me too, it still happen in the latest version 5.1.0

**Comment by MehVahdJukaar** [comment]
Send new log pls

**Comment by thelegitdolt** [comment]
https://gist.github.com/thelegitdolt/423bec0032df5fe234c6642034204780

After updating, it's complaining about my datapack instead

**Comment by MehVahdJukaar** [comment]
Update moonlight and Supplementaries

**Comment by thelegitdolt** [comment]
Updating moonlight seemed to have fixed it
