### ISSUE TITLE
[Suggestion] Config to give the player an Atlas when creating a world

### ISSUE THREAD

**Issue by LioxAcc** [MehVahdJukaar/mapatlases-neoforge#153]
I know there are mods like "Starter kit"
that allow you to give any item to the player at the start
however I would really appreciate if this mod included a setting to give the player an atlas when creating a new world

**Comment by MehVahdJukaar** [comment]
I think this is quite out of scope and redundant as, as you say there are mods that can do that. Plus this is something that could even be done with a datapack
