### ISSUE TITLE
Caused by 0: java.lang.NoClassDefFoundError: net/mehvahdjukaar/moonlight/api/platform/RegHelper

### ISSUE THREAD

**Issue by IamNarutoUzumaki** [MehVahdJukaar/mapatlases-neoforge#156]
[crash-2024-09-28_11.39.45-fml.txt](https://github.com/user-attachments/files/17173817/crash-2024-09-28_11.39.45-fml.txt)
[latest.log](https://github.com/user-attachments/files/17173818/latest.log)

**Comment by MehVahdJukaar** [comment]
looks like you didnt have moonlight lib installed which is a dependency of the mod
