### ISSUE TITLE
Suggestion: ability to add pins to minimap.

### ISSUE THREAD

**Issue by AngelOfCreation** [MehVahdJukaar/mapatlases-neoforge#157]
Holding ALT and clicking on a pin should display it on the minimap, and if its offscreen it should rotate with your orientation so you know which direction to go.

**Comment by MehVahdJukaar** [comment]
But that's literally how it works already

**Comment by AngelOfCreation** [comment]
Mate, I'm literally using the Atlas right now and it doesn't do that. The pins only show up if you're in the map that contains them.

**Comment by MehVahdJukaar** [comment]
Are you clicking on the pins on the left hand side of the atlas?

**Comment by AngelOfCreation** [comment]
No, that just makes the map move over to them. There's no option to make pins appear on the minimap wherever you are.

**Comment by MehVahdJukaar** [comment]
pressing p will add pins. same when clicking  on the big red pin icon
