### ISSUE TITLE
[1.19.2] Atlas Lecterns issues

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/mapatlases-neoforge#16]
- They have missing textures when you place them in the world 
<img width="1512" alt="Screen Shot 2023-09-23 at 03 01 35" src="https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/50085439/97a811da-64ba-4924-bd8c-7acde2ed552d">

- Unable to take atlases from the lectern
Normal lecterns books have a "take book" button, as shown below: 
<img width="844" alt="Screen Shot 2023-09-23 at 03 06 13" src="https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/50085439/7a3b5de8-f3f3-4a07-aae7-e9f465a9c4ae">
This is not the case for map atlas lecterns.
<img width="1512" alt="Screen Shot 2023-09-23 at 03 08 21" src="https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/50085439/4e387b85-9289-4a3d-8c03-46c3b81477f5">

Using Map Atlas version 5.2.0

**Comment by MehVahdJukaar** [comment]
should be fixed

**Comment by thelegitdolt** [comment]
am now in 5.3.0. 
After you place an atlas on a lectern, the lectern will always show the atlas book texture even if you switch out with a normal book

https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/50085439/aa495070-3854-46c3-ab86-997907907f81

**Comment by thelegitdolt** [comment]
The bug I described was fixed
