### ISSUE TITLE
Newer version of 1.19.2 version of the mod doesn't seem to work.

### ISSUE THREAD

**Issue by Thombros** [MehVahdJukaar/mapatlases-neoforge#161]
[crash-2024-11-04_00.16.19-fml.txt](https://github.com/user-attachments/files/17621859/crash-2024-11-04_00.16.19-fml.txt)

The mod only works when I go back to 1.19-5.6.8-all.

![image_2024-11-04_103347968](https://github.com/user-attachments/assets/e63bbe1a-5787-42aa-a1d4-b084547259bb)

**Comment by MehVahdJukaar** [comment]
install moonlight lib

**Comment by Thombros** [comment]
I do have moonlight lib.

**Comment by Thombros** [comment]
Ok nvm GDL did the thing where it "downloaded" a mod as a dependency but didn't pick a version so it just, didn't really exist in the folders. Thanks.
