### ISSUE TITLE
[Forge 1.20.1] is there a way to let the atlas automatically generate slice maps depending on the current y level of the player

### ISSUE THREAD

**Issue by mumumuri** [MehVahdJukaar/mapatlases-neoforge#162]
i have this mod and the supplementaries mod on my server now i have the atlas set to automatically generate the maps so that i dont have to craft them. i now want to set it to where it also generates maps when i get in caves/the nether and so on i dont want to always have to put in a slice map is that possible?

**Comment by MehVahdJukaar** [comment]
add maps to it and switch to a slice Y level you already have. Then maps will be generated for that level
