### ISSUE TITLE
Map atlas Full?

### ISSUE THREAD

**Issue by RaptorMother** [MehVahdJukaar/mapatlases-neoforge#165]
![image](https://github.com/user-attachments/assets/4cdb624c-d470-40e3-9fb1-65ddf85486a2)

As seen in the image, the atlas seems to be full? I found no mention of this in the mod, and it seems to prevent further mapping progress. Is there a setting to remove this limit or is it hardcoded? I really like to use a more immersive map mod, but if there's an upper limit, that really forces me...

**Comment by MehVahdJukaar** [comment]
Yeah there should be a config tho be mindful of that as the more maps it holds it could potentially slow down
