### ISSUE TITLE
[1.19.2-5.2.0] Crash when adding markers to unmapped chunks

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/mapatlases-neoforge#17]
To reproduce: 
- Craft an atlas
- Add a marker somewhere that has not been filled out yet. 

Crash Report: https://gist.github.com/thelegitdolt/9d66e4dd79f07c6302744092e9be9806

**Comment by MehVahdJukaar** [comment]
weird i couldnt replicate

**Comment by MehVahdJukaar** [comment]
unless that happened in a lectern

**Comment by thelegitdolt** [comment]
Yhea it was in a lectern
