### ISSUE TITLE
Mod Crashing

### ISSUE THREAD

**Issue by R3fresco** [MehVahdJukaar/mapatlases-neoforge#171]
Its seems that the mod Map Atlases 1.20.1 for forge crash with Optifine, Any fix?

**Comment by MehVahdJukaar** [comment]
dont use optifine. Ever. There is no reason whatsoever anybody should ever use that thing, either with or wtihout mods. There are way way better optimization mods and way way better visual customization mods.
That mod has mo care whatsoever for compatibility and the way its done its more comparable to a mod loader like forge which alters game code so this means mods are not built on it and can and will crash in cases. Also i'm tired of explaining this
