### ISSUE TITLE
[1.19.2-5.2.0] Cannot shift-click an atlas into the top slot of cartography tables 

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/mapatlases-neoforge#18]
In vanilla, when in the cartography table GUI, shift clicking any items that could be used inside it (Glass panes, maps, et cetera) will instantly place the item inside the slots. This is not the case for the atlas added by this mod.

**Comment by MehVahdJukaar** [comment]
Should be fixed

**Comment by thelegitdolt** [comment]
it has
