### ISSUE TITLE
[1.19.2]: Problem with (certain?) dimension (nether?) modifications

### ISSUE THREAD

**Issue by SiverDX** [MehVahdJukaar/mapatlases-neoforge#19]
Maybe when said modifications change the height?

When use the teleport functionality it puts me above the bedrock roof
I'm using https://modrinth.com/datapack/nether-3.0 but a (no longer available?) 1.19 version

Datapack: [nether-3-4.zip](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12706344/nether-3-4.zip)

![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/22003703/0e18bc31-a24b-41c7-89a2-3f8769ffdeb8)

![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/22003703/841c5c66-959b-4900-bbd5-81bd7d4361d3)

---

Xaero map:

![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/22003703/a9bc8c0a-40ea-433c-ada8-e7aa040508d0)

**Comment by MehVahdJukaar** [comment]
Teleport function is a bit jankie when targeting unloaded chunks ad the game doesn't know the stufsce height yet so it can put you at weird places. For ones with ceiling however putting you on the ceiling is the correct behsvior as that's the surface level

**Comment by SiverDX** [comment]
The issue is more about what the map is showing
I mentioned what the teleport does in case it helps finding the cause (e.g. the map thinking youre constantly at bedrock-roof level)

**Comment by MehVahdJukaar** [comment]
It doesn't think that's how maps in the nether work in vanilla

**Comment by SiverDX** [comment]
woops my bad, I saw the screenshots at the end of the mod description and didn't notice you need https://modrinth.com/mod/better-nether-map to make it work like that
