### ISSUE TITLE
Invalid Player data with latest patch 1.20.1 forge

### ISSUE THREAD

**Issue by celsiusqc** [MehVahdJukaar/mapatlases-neoforge#2]
[debug.log](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12476500/debug.log)
4.0.3

**Comment by l-xue** [comment]
minimal example on a fresh instance:
[debug.log](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12478784/debug.log)

versions:
MC 1.20.1
Forge 47.1.3
Map Atlases 4.0.3

**Comment by MehVahdJukaar** [comment]
This should have been fixeda while back
