### ISSUE TITLE
[Suggestion] Easy Extract Map from Atlas

### ISSUE THREAD

**Issue by ffuentesm** [MehVahdJukaar/mapatlases-neoforge#20]
I absolutely adore this mod and have closely followed its evolution ever since it was first introduced on Forge. I wish that Vanilla Minecraft incorporated this as a feature, it is truly an immersive way to have a World Map.

My only suggestion is to make the process of removing a map more user-friendly compared to the current method of using Shears + Atlas within your crafting inventory. It would be wonderful if we could place the Atlas on the cartographer's table, with Shears positioned below it. This arrangement would open up the Atlas Storage UI, allowing us to easily scroll through and select a specific map for removal.

**Comment by MehVahdJukaar** [comment]
try new version
