### ISSUE TITLE
Configured Crash

### ISSUE THREAD

**Issue by CodexArchive** [MehVahdJukaar/mapatlases-neoforge#21]
I recently updated the mod to 1.19-5.3.0 but when I go into the in-game mod menu to access the configs via the mod Configured, it causes my game to crash every time.

**Comment by MehVahdJukaar** [comment]
I need latest.log

**Comment by CodexArchive** [comment]
[crash-2023-09-23_17.36.08-client.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12707313/crash-2023-09-23_17.36.08-client.txt)

**Comment by CodexArchive** [comment]
One other minor thing I happened to notice was that, while the atlas registers as a "hands" item with Curios installed, Curios doesn't actually generate a baubles slot for it.

**Comment by MehVahdJukaar** [comment]
Does this apply to newer version?

**Comment by CodexArchive** [comment]
Just updated to 1.19-5.4.0; interaction with Configured functions properly now, though trying to load up with Curios deploys the error "Curios API (curios) encountered an error during the sided_setup event phase       org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered".

[latest.log](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12707578/latest.log)

[crash-2023-09-23_21.29.41-fml.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12707579/crash-2023-09-23_21.29.41-fml.txt)

**Comment by MehVahdJukaar** [comment]
says its a curio/ mixin extras error

**Comment by CodexArchive** [comment]
Just saw the update 1.19-5.4.3 so I updated and tried to load in, but it output the same Curios error screen

[latest.log](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12709669/latest.log)

[crash-2023-09-24_17.01.57-fml.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12709670/crash-2023-09-24_17.01.57-fml.txt)

**Comment by MehVahdJukaar** [comment]
Idk what's that's about. It's ajar in jar issue with mixin extras and possibly curios. Try without curios

**Comment by CodexArchive** [comment]
Removing Curios does allow the game to boot up, though that revealed a new issue. In the creative world I loaded, as soon as the atlas was placed in my inventory, it crashed the game instantly. I tried to craft one as well, but attempting to interact with anything that had an inventory (crafting table, chest, hopper, etc.) also caused the game to crash.

[latest.log](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12709742/latest.log)

[crash-2023-09-24_17.51.17-client.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12709743/crash-2023-09-24_17.51.17-client.txt)

**Comment by Novarleeir** [comment]
> Removing Curios does allow the game to boot up, though that revealed a new issue. In the creative world I loaded, as soon as the atlas was placed in my inventory, it crashed the game instantly. I tried to craft one as well, but attempting to interact with anything that had an inventory (crafting table, chest, hopper, etc.) also caused the game to crash.
> 
> [latest.log](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12709742/latest.log)
> 
> [crash-2023-09-24_17.51.17-client.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12709743/crash-2023-09-24_17.51.17-client.txt)

I'm having this same issue on map_atlases_forge-1.20-5.4.1
I do have curios installed and everything works as it should, but placing an atlas in your inventory crashes the game. On rejoining the world, the atlas works fine. However, exploring any newly generated maps/chunks causes another crash so it must be tied to the atlas generating new maps.

**Comment by CodexArchive** [comment]
> > Removing Curios does allow the game to boot up, though that revealed a new issue. In the creative world I loaded, as soon as the atlas was placed in my inventory, it crashed the game instantly. I tried to craft one as well, but attempting to interact with anything that had an inventory (crafting table, chest, hopper, etc.) also caused the game to crash.
> > [latest.log](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12709742/latest.log)
> > [crash-2023-09-24_17.51.17-client.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12709743/crash-2023-09-24_17.51.17-client.txt)
> 
> I'm having this same issue on map_atlases_forge-1.20-5.4.1 I do have curios installed and everything works as it should, but placing an atlas in your inventory crashes the game. On rejoining the world, the atlas works fine. However, exploring any newly generated maps/chunks causes another crash so it must be tied to the atlas generating new maps.

That's interesting. After reading what you said, I went back in my test world and, I don't know what changed, but the atlas is now working as intended (without curios active though), however something is still causing the game to crash when I interact with anything that has some form of inventory.

[latest.log](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12709840/latest.log)

[crash-2023-09-24_19.08.28-client.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12709841/crash-2023-09-24_19.08.28-client.txt)

**Comment by Novarleeir** [comment]
I have no issue opening inventories, it seems to only be when generating new atlas map sections.

Here are my latest logs:
[latest.log](https://mclo.gs/llfltfk)
[crash-2023-09-24_15.42.06-client.txt](https://mclo.gs/3PqTc0b)

**Comment by MehVahdJukaar** [comment]
darn fixing an issue creates another :_:

**Comment by CodexArchive** [comment]
Just updated to 1.19-5.5.0-all; everything is now working as expected and all prior crashing issues I encountered appear to have been resolved. Only thing the update hasn't changed is that Curios still doesn't generate a "hands" slot for the atlas to go in, but that's honestly a fairly minor thing.
