### ISSUE TITLE
[5.4.2] Server crash on startup

### ISSUE THREAD

**Issue by abrossimow** [MehVahdJukaar/mapatlases-neoforge#22]
Problem:
Server crashing on startup, pointing to Supplementaries mod (?)

-> Client boots normally.
-> Server is modded

Forge version: 43.2.12

Log:
[2023-09-24-1.log](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12708861/2023-09-24-1.log)

**Comment by MehVahdJukaar** [comment]
Update moonlight

**Comment by abrossimow** [comment]
Oversight on my end, sorry! That fixed it, thank you for the quick reply!
