### ISSUE TITLE
Minimap impossible to see if set to other corners.

### ISSUE THREAD

**Issue by Sixdd6** [MehVahdJukaar/mapatlases-neoforge#24]
If the Minimap display corner is anything other than top left it will be cut off. The problem stems from the fact that the offsets for horizontal and vertical only calculate from the left and top. These settings should be made dynamic depending on the position of the minimap so that the map can be properly aligned when set to another corner of the screen.

Steps to reproduce:
Set minimap corner to top right/bottom left/bottom right
Try to align the minimap to be visible and notice the map moves only left to right and top to bottom so cannot be aligned from the right to left or bottom to top as necessary for these other corners.

Suggestion:
Either make the offsets capable of negative values or make the values given react to the corner of screen chosen. With the second suggestion it would allow for simpler user configuration, if the user has a preffered amount of offset then it should work regaurdless of display corner chosen.

**Comment by MehVahdJukaar** [comment]
fixed, all default values have had their parameters tweaked
