### ISSUE TITLE
[Suggestion] Atlas accept Treasure maps

### ISSUE THREAD

**Issue by ffuentesm** [MehVahdJukaar/mapatlases-neoforge#26]
I have been wondering if would be possible to add treasure/village maps on the atlas, so that it would show the X icons on the map, as well as villages and other structure icons on the world map.

**Comment by MehVahdJukaar** [comment]
that can already be done

**Comment by ffuentesm** [comment]
It can? I am trying to add this buried treasure map to it and it's not happening. 
I also tried on the crafting grid. 
![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/44974827/9a290e6d-349d-4e9f-a08a-1c6c6fd44d09)

**Comment by MehVahdJukaar** [comment]
they have to have the same scale

**Comment by ffuentesm** [comment]
is the map scale from buried treasure different from non-modified empty maps?

**Comment by MehVahdJukaar** [comment]
i
![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/24719182/2a6412b8-5ac0-4d31-a62d-bad22e8b8915)

**Comment by ffuentesm** [comment]
How did you get that info to show?
Mine just shows this. 
![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/44974827/f892f272-341d-4a1b-a4b3-8d701ae06796)

**Comment by MehVahdJukaar** [comment]
That's vanilla tooltip. The one you have is the weird one
