### ISSUE TITLE
[1.20.x] Crash when Atlas entered a different curio slot

### ISSUE THREAD

**Issue by ffuentesm** [MehVahdJukaar/mapatlases-neoforge#27]
I accidentally SHIFT+Lclick on the atlas when Curio was open, and it accidentally went into a Blank Curio slot instead of the Hand Slots, which caused the game to crash. 
![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/44974827/c173039b-e13b-47d0-9efe-e8db741ff5ce)
Map Atlases 1.20-5.4.1
Log: https://crashy.net/70fd2fc5-7c35-420c-a3f9-1f1b8cebfc44

**Comment by MehVahdJukaar** [comment]
try new version
