### ISSUE TITLE
[1.20.x] Lecturn Atlas button GUI glitch

### ISSUE THREAD

**Issue by ffuentesm** [MehVahdJukaar/mapatlases-neoforge#28]
When placing the atlas on the lecture the GUI buttons are overlapping with the map image. 
map_atlases_forge-1.20-5.4.2
![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/44974827/0aff21bd-6b03-4279-82a5-ba5b1270a102)

**Comment by ffuentesm** [comment]
Even in map_atlases-1.20-5.5.3-all, the glitch still there. 
![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/44974827/7b765187-c3b6-487a-a53f-bf75c80779a3)

**Comment by MehVahdJukaar** [comment]
Hm weird something must be off as I couldn't replicate
