### ISSUE TITLE
[Crash] Opening Atlas in Creative for the First Time In World

### ISSUE THREAD

**Issue by kawaiicakes** [MehVahdJukaar/mapatlases-neoforge#29]
**Forge 1.19.2, Moonlight 2.2.46, Map Atlases 5.4.3**

To reproduce the crash, all you need to do is open an Atlas while in creative mode. My circumstances are as follows: 

- It was the first time ever opening an atlas on this world
- The world was not generated with the mod installed; it was added later
- I was in the overworld 
- I'm pretty sure I had made maps in the world prior to installing the mod

Crash log is attached [here.](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12718141/crash-2023-09-25_11.38.13-client.txt)

If any further information is required please do not hesitate to reach out. Thanks.

**Comment by MehVahdJukaar** [comment]
does this hapen with newest mod version?

**Comment by kawaiicakes** [comment]
> does this hapen with newest mod version?

Seems fine actually, thanks! As an aside, I have the crashlog of another player of mine [here](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12741729/crash-2023-09-27_19.43.38-client.txt)
