### ISSUE TITLE
[1.20.1] Atlas not Saving unlocked maps

### ISSUE THREAD

**Issue by ffuentesm** [MehVahdJukaar/mapatlases-neoforge#32]
map_atlases-1.20-5.5.1-all
For some reason, when I reopen my world, the atlas is missing map pages. 
I while ago, the atlas had 50 full maps, now when I opened it after closing the game, it only had 10. The number of empty maps stays the same.

**Comment by MehVahdJukaar** [comment]
does this happen with newest version? There have been many client sync issues but this should never affect the actual maps that are stored serverside

**Comment by MehVahdJukaar** [comment]
if that was an atlas made with the old mod version thats normal as they are converted when you open it
