### ISSUE TITLE
Crash with No See, No Tick

### ISSUE THREAD

**Issue by HUYBUSSIN** [MehVahdJukaar/mapatlases-neoforge#33]
When creating a new map from the Atlas it turns out to crash.
Minecraft 1.19.2 Forge 43.3.0
Map Atlas 5.4.3
Here is the Crash Report:
https://[bytebin.lucko.me/d9bSrBjEHK](https://bytebin.lucko.me/d9bSrBjEHK)

**Comment by MehVahdJukaar** [comment]
Try new version
