### ISSUE TITLE
[Feature question]: Custom map pins

### ISSUE THREAD

**Issue by SiverDX** [MehVahdJukaar/mapatlases-neoforge#36]
Will custom map pins which you can give a name be a thing?
As I understand it right now you can use blocks (+ additional ones if you have Supplementaries) as map markers (e.g. banners or lodestones?)

But when I'm running around in the wild and want to mark a certain spot how could I do that?
Is that achieved by Supplementaries sliced maps (1.20.x only I think)?

**Comment by MehVahdJukaar** [comment]
you can add custom ones using moonlight custom map markers which are all data driven. you can also use the pin button to place them as the config allows it to play any pin. You can however give any names. Not sure how far i want to go with this as i dont want to take markers away from their block form. So to have a named one you would need to have one of the suported named lblocks with you. Might look into a gui for text using the red pin button but i dont want to give them all for free like that

**Comment by SiverDX** [comment]
Yeah I saw the red pin
Didn't clarifiy it correctly but what I meant is setting pins with custom names without the usage of blocks

Maybe there is some sort of resource you could use? Or an item which has x amount of uses (like a pen)?
They could even degrade after x amount of time making only block pins permanent
