### ISSUE TITLE
[1.19.2-5.5.0] "Take Book" button in atlas lecterns is rendered on top of the map 

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/mapatlases-neoforge#40]
<img width="1512" alt="Screen Shot 2023-10-08 at 16 05 33" src="https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/50085439/2f2c1df4-894f-4e20-8441-b570a97108a8">

**Comment by MehVahdJukaar** [comment]
should be resolved in newest version

**Comment by thelegitdolt** [comment]
It is not

**Comment by thelegitdolt** [comment]
(using newest version 5.5.2)

**Comment by MehVahdJukaar** [comment]
Ah need to backport the fix. Issue only happened when gui size is not 4

**Comment by thelegitdolt** [comment]
seems to be fixed in latest version
