### ISSUE TITLE
[1.19.2] Crash when opening client config with Configured

### ISSUE THREAD

**Issue by SentientBowtie** [MehVahdJukaar/mapatlases-neoforge#42]
Map Atlases version: `1.19-5.5.0-all` (the one uploaded [Oct. 9th '23](https://www.curseforge.com/minecraft/mc-mods/map-atlases-forge/files/4789302))
Moonlight Lib version: `moonlight-1.19.2-2.2.46-forge`
Configured version: `Configured 2.1.1`
(I am also using Supplementaries version `supplementaries-1.19.2-2.3.24`.)

[Crash log.](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12872671/crash-2023-10-11_12.46.28-client.txt)

Attempting to edit Map Atlases' client-side configuration in-game via [Configured](https://www.curseforge.com/minecraft/mc-mods/configured) causes a crash. This did not happen with the previous version, `map_atlases-1.19-5.5.0-all.jar` (the one uploaded [Sep. 27th '23](https://www.curseforge.com/minecraft/mc-mods/map-atlases-forge/files/4771031)).

**Comment by MehVahdJukaar** [comment]
fixed
