### ISSUE TITLE
1.20.1 atlas bug

### ISSUE THREAD

**Issue by Qskar1** [MehVahdJukaar/mapatlases-neoforge#45]
![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/80540374/46411415-88f3-4a84-bde6-9904efca5402)
(Fabric 0.14.22, MC 1.20.1)

After creating an atlas in my survival world, I got kicked out and this message popped up. I succesfully replicated it on a test world.

**Comment by MehVahdJukaar** [comment]
does this still happen? check if supplementaries is updated there was a problem with colored maps

**Comment by Qskar1** [comment]
> does this still happen? check if supplementaries is updated there was a problem with colored maps

Oh yeah it works now, thanks. Also coo-ass mod
