### ISSUE TITLE
1.20.1 Massive screen tearing and visual glitches when map hud is rendered

### ISSUE THREAD

**Issue by frangnosquest** [MehVahdJukaar/mapatlases-neoforge#46]
Seems to be an issue with Supplementaries (removing either fixes the problem).
In certain areas of my world, having the atlas in  hotbar causes the game to suddenly freeze along with screen tearing and visual glitches (tried to record it in obs but only the game freezing was recorded).
No crash, but the game console spits out the following every tick:
"<log4j:Event logger="net.minecraftforge.client.gui.overlay.ForgeGui" timestamp="1697448839747" level="ERROR" thread="Render thread">
    <log4j:Message><[CDATA[Error rendering overlay 'map_atlases:atlas']]></log4j:Message>
    <log4j:Throwable><[CDATA[java.lang.ArrayIndexOutOfBoundsException
]]></log4j:Throwable>
  </log4j:Event>"

**Comment by MehVahdJukaar** [comment]
i need latest.log

**Comment by frangnosquest** [comment]
[latest.log](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/12935353/latest.log)
my bad, here you go

**Comment by frangnosquest** [comment]
Letest updates (either supplementaries or atlas itself) seem to have fixes the issue, closing this for now.
