### ISSUE TITLE
not enought info

### ISSUE THREAD

**Issue by GreenForzeGaming** [MehVahdJukaar/mapatlases-neoforge#49]
ive looked around and cant find any of the methods on pictures used on curseforged. like what curios slot? there is none with curios installed. and sliced maps how do i even add those. id love for there to be more info couse i cant find anything all. i know that its some how available... but cand find info about it anywhere. thx

**Comment by robosoup2** [comment]
![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/50124081/0289c2db-9d25-475d-8426-1bbf7c31a5f6)
It has a link to what you want right here haha
but I came here to add, the 2 datapack links here are both broken, they say "not found"

**Comment by MehVahdJukaar** [comment]
im in process od chnging description to include all new features ina  more comprehensive manner and remove old packs that no longer work

**Comment by GreenForzeGaming** [comment]
thank you so much. i had no idea they where links, did hover over text but my mouse didnt change icon or say that ithere where links.
