### ISSUE TITLE
Direccion del mini map

### ISSUE THREAD

**Issue by GhiltonAbyss** [MehVahdJukaar/mapatlases-neoforge#51]
se puede cambiar el lugar donde se hubica el mini map de atlas por que busco en configuraciones y no los ayo

**Comment by DankestO** [comment]
¿Te refieres a cuando está en el inventario el atlas?
Si es así es en map_atlases-client.toml, busca:

	**#Allowed Values: UPPER_LEFT, UPPER_RIGHT, LOWER_LEFT, LOWER_RIGHT
	anchoring = "UPPER_RIGHT"**

Sustituyendo "UPPER_RIGHT" por alguno de los que te pone de ejemplo arriba se puede ir moviendo el mapa por las esquinas.

La otra manera es:

	**#An integer which will offset the mini-map horizontally
	#Range: -4000 ~ 4000
	horizontal_offset = 5
	#An integer which will offset the mini-map vertically
	#Range: -4000 ~ 4000
	vertical_offset = 5**

Aumentando y disminuyendo el valor de "horizontal_offse" y "vertical_offset" debería irse moviendo el mapa de forma mas personalizada.
