### ISSUE TITLE
[REQUEST] Config for Map Atlases on FORGE.

### ISSUE THREAD

**Issue by ceifadorcinixtru** [MehVahdJukaar/mapatlases-neoforge#53]
Make a config folder for map atlases for forge. i know that fabric has a config folder, but forge doesnt, pls add this for forge.

**Comment by MehVahdJukaar** [comment]
hm why tho? it would just contain 2 files

**Comment by ceifadorcinixtru** [comment]
because in Fabric we have the option to make the map "infinite", without needing to add new blank maps.

**Comment by MehVahdJukaar** [comment]
and so can you here. Forge version only has new features and a bunch more at that

**Comment by ceifadorcinixtru** [comment]
but how can i change this without the config folder?

**Comment by MehVahdJukaar** [comment]
Using the mod config files. There's 2 of them in the configs directory
