### ISSUE TITLE
Corrupted textures on zoomed out maps

### ISSUE THREAD

**Issue by cdf1008** [MehVahdJukaar/mapatlases-neoforge#55]
I am having problems where the map is rendering corrupt graphics after certain zoom levels. The graphics could be anything from corrupt Mojang screens to random textures.

These photos are on forge 47.2.4 with only the mods Map Atlases 5.10.2 and Moonlight Library 2.8.56 with no config changes 

Here is my latest.log as well
[latest.log](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/13245322/latest.log)

1.3.5 Zoom
![1 3 5 Zoom](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/8197404/37c03164-8687-4d39-947c-845cb31dcf6f)
1.4.5 Zoom
![1 4 5 Zoom](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/8197404/2fdbbf65-0c04-42b0-9fd0-21e517286592)
1.5.5 Zoom
![1 5 5 Zoom](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/8197404/288eb309-baea-466c-ba42-c76be7f3f28d)

This also happens on the Minimap and Lectern
Minimap
![Minimap](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/8197404/4375cde5-a68e-4433-8143-b1e29909037a)
Lectern
![Lecturn](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/8197404/6844c662-3e80-4532-99f8-7eaa4b0f3839)

**Comment by MehVahdJukaar** [comment]
temporary fix: turn off map mimpap in moonlight lib.
Also do you have supplementaries? if so why the heck isnt that map colored.
Do you have immediately fast? doesn it work without? that mod does some butchering to map render code

**Comment by MehVahdJukaar** [comment]
btw what you see is the content ofyour vram where a texture has not been filles so ist just garbage from previous textures

**Comment by cdf1008** [comment]
Thanks you for the quick response with the temp fix it solved the issue! I only had the two mods I said in the post, as I was seeing if it was a issue that persisted with just the mod itself and Moonlight libraries outside of a larger modpack so no supplementaries for this issue

**Comment by MehVahdJukaar** [comment]
also i cant replicated. just booted up a modpack with those mods and a few random others and map mipmp is generated fine

**Comment by cdf1008** [comment]
I asked a friend to help me check it to confirm it wasn't a single system issue he had similar issues of about 3-5 map tiles having the rendering problem around him, which was resolved again with the temp fix.  

Usually to test I am logging into the same single player world, generating several maps on the same atlas, confirming the issue, changing the Moonlight Library mipmap config, re-logging, and repeating. 

The rendering issue seems to happen sporadically in values of 1 and 2 on the mipmap, often reducing the size of the vram dump texture to only nearby generated tiles, while 3 and 4 often making it identical to above images.

Regardless, setting mipmap to 0 makes the Atlas work correctly with no vram dumps on the map. I should note as well, if it matters, that I usually have Minecraft's normal mipmap at 4 and don't see any of the issues above in the regular game. I am unsure of how to proceed if you cannot replicate, is there any additional logs or information I can send that can help?

**Comment by MehVahdJukaar** [comment]
So if I get this right you do see some maps correctly when zoomed out? Can you replicate this with just moonlight (and atlas. Altho you just need to place a map and walk away)

**Comment by cdf1008** [comment]
Yeah I do see a map or two correctly at random now that ive been testing it a bit, Here is a gif example of it on mipmap 3.
![d9fcfb313fafb0ec74a2ea9a329459f0](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/8197404/27e9f983-6a25-401a-ac9c-8c9b1624a8ad)
and here is the map on mipmap 0 for comparison sake
![2fffc35a475c2fe1fba38136ffa6c849](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/8197404/ae616365-bb1a-4e14-93b0-db74a7852181)

**Comment by MehVahdJukaar** [comment]
not sure.  I tried loading up a modpack with the mod and zooming out at max and all maps seemed to behave fine, texture had mipmap too even for newly created ones

**Comment by MehVahdJukaar** [comment]
can you try new moonlight version?

**Comment by cdf1008** [comment]
I tried it and it works. I am able to properly able to use use mipmap 3 and 4 without any issues showing. Thank you very much!
