### ISSUE TITLE
Crashes with mod pack. on newer versions passed (5.4.0)

### ISSUE THREAD

**Issue by TheaRTGGaming** [MehVahdJukaar/mapatlases-neoforge#56]
Here is the Video showing it crashing and crash log

([Video](https://youtube.com/clip/UgkxATFvtdnCnQ1tFQi0gwjMlZ9pNbTFlRjq?si=KJhWXrjX88tshRxJ))

[crash-2023-11-01_22.41.09-client.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/13246110/crash-2023-11-01_22.41.09-client.txt)

**Comment by MehVahdJukaar** [comment]
optifine

**Comment by TheaRTGGaming** [comment]
but some how it works with optifine on version 5.4.0

**Comment by MehVahdJukaar** [comment]
Because mod had less features which included one that used a class which origine nuked. Stop using optifine with mods. Or at all. It's bad
