### ISSUE TITLE
The game crashes when I try to switch to another slot

### ISSUE THREAD

**Issue by Dany0s1** [MehVahdJukaar/mapatlases-neoforge#60]
I'm tired of the latest version of the mod, and when I try to switch to another slot the game crashes. I can move a book to inventory, put it in my hand, open it and move around inside it, but when I try to use the mouse wheel to switch, the game crashes

**Comment by Dany0s1** [comment]
[Текстовый документ.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/13272042/default.txt)

**Comment by Dany0s1** [comment]
There may be a problem with the card appearing in the left corner. Usually the map is shown in the upper left corner, but now there is no such map, and when the game tries to move it there, so to speak, the game crashes. Unfortunately I don't know how to fix this

**Comment by MehVahdJukaar** [comment]
that file you send is empty

**Comment by Dany0s1** [comment]
[when the game crashed if I moved to a slot with a book.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/13284861/when.the.game.crashed.if.I.moved.to.a.slot.with.a.book.txt)
[The game just started crashing.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/13284863/The.game.just.started.crashing.txt)

**Comment by MehVahdJukaar** [comment]
update moonlight. Update supplementaries. Infact update all mods as you should. Also heads up be wary you are using optifine

**Comment by Dany0s1** [comment]
Strange. I don't use Moonlight, and Optifine wasn't in the build when the game crashed. Perhaps you really need to update the rest of the mods. But it’s strange that before that everything worked well, that is, Before I updated the mod on Altas everything worked ± perfect

**Comment by MehVahdJukaar** [comment]
is this still happening with latest version?

**Comment by Dany0s1** [comment]
The latest version works great. Thank you!
