### ISSUE TITLE
1.18.2 malfunction

### ISSUE THREAD

**Issue by JoseVEstevam** [MehVahdJukaar/mapatlases-neoforge#61]
Operation is different from other versions, lacking several of the normally available options
![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/117928779/39b7fafd-084c-42b6-aab9-4e210381b68b)
![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/117928779/58bc1e98-57d8-4a75-917f-2ef11277885e)
![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/117928779/7022d506-1fd6-4af0-8777-3bdfff8472c5)

**Comment by MehVahdJukaar** [comment]
And so is the game itself. It's an old cersion
