### ISSUE TITLE
[1.20.1] - Placing a pin crashes the Minecraft client

### ISSUE THREAD

**Issue by WaspYarp** [MehVahdJukaar/mapatlases-neoforge#67]
Just what the text says
Crash log upload:
[crash-2023-12-20_00.51.03-client.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/13722697/crash-2023-12-20_00.51.03-client.txt)

**Comment by WaspYarp** [comment]
"WITH MODS" i dont tested alone

**Comment by MehVahdJukaar** [comment]
Update moonlight

**Comment by WaspYarp** [comment]
It works now, sorry for bothering
