### ISSUE TITLE
crash when launching optifine and forge vers map atlases 2.20.1 forge

### ISSUE THREAD

**Issue by wallythestunted** [MehVahdJukaar/mapatlases-neoforge#68]
[crash-2023-12-20_21.26.08-client.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/13731301/crash-2023-12-20_21.26.08-client.txt)
[crash-2023-12-20_21.57.00-client.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/13731305/crash-2023-12-20_21.57.00-client.txt)
[crash-2023-12-20_22.11.00-client.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/13731309/crash-2023-12-20_22.11.00-client.txt)

21.26 is my mods
21.57 preview 6 optifine 
21.11 is optifine 5
any fixes? without supplementaries and the like it still crashes on launch
btw how do i delete pins?

**Comment by MehVahdJukaar** [comment]
Don't use otpifine. It's bad and nobody should use it. To delete pins hold shift

**Comment by wallythestunted** [comment]
thx, if you dont mind me asking are there any optifine alternatives on forge? my game runs like ass on fabric

**Comment by wallythestunted** [comment]
closed by accident srry

**Comment by wallythestunted** [comment]
i closed it by accident mb

**Comment by MehVahdJukaar** [comment]
https://mehvahdjukaar.github.io/McPerformanceMods/#setup right tab

**Comment by wallythestunted** [comment]
thank you mate youre awesome

**Comment by wallythestunted** [comment]
thank you mate youre awesome
