### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by knoxhack** [MehVahdJukaar/mapatlases-neoforge#7]
crash on game start

crash log: 
[https://gist.githubusercontent.com/knoxhack/c3ef35269f899db380f763a46e183032/raw/7b06bd8d13b7546291ded5cbfafa4d62713f56c7/mapatlases](https://gist.githubusercontent.com/knoxhack/c3ef35269f899db380f763a46e183032/raw/7b06bd8d13b7546291ded5cbfafa4d62713f56c7/mapatlases)

**Comment by MehVahdJukaar** [comment]
Be sure your other moda are uodated
