### ISSUE TITLE
how to obtain the Antique Atlas look

### ISSUE THREAD

**Issue by Arekkusubillaga** [MehVahdJukaar/mapatlases-neoforge#79]
I'm sorry for asking something obvious , but I tried to craft it combining the ink from supplementaries but nothing happened ? or how I'm supposed to use it ?

**Comment by MehVahdJukaar** [comment]
Are you using latest 1.20 version?

**Comment by Arekkusubillaga** [comment]
1.19.2 the last version for that version of minecraft

**Comment by MehVahdJukaar** [comment]
Then you cant
