### ISSUE TITLE
Crash when installing the mod on Fabric 1.20.4

### ISSUE THREAD

**Issue by vico93** [MehVahdJukaar/mapatlases-neoforge#81]
Got [this crash](https://gist.github.com/vico93/d9b33320794f3aeb00e1470b8328de19) after placing Map atlases and its dependencies on my modpack.

MC 1.20.4
Fabric Loader 0.15.5-1.20.4
Fabric API 0.94.0+1.20.4
moonlight-1.20.4-2.9.3-fabric.jar
cardinal-components-api-5.4.0.jar
Map Atlases [map_atlases-1.20-2.7.13-fabric.jar](https://legacy.curseforge.com/minecraft/mc-mods/map-atlases/files/5035846)

**Comment by vico93** [comment]
Further information: The crash happens when i click on the "Data Pack" button in new world screen. Note that i'm using [Dataloader](https://github.com/Commander07/data-loader) ([MR](https://modrinth.com/mod/dataloader)), a mod that automatically loads datapacks from a `datapacks` folder in the profile folder.

**Comment by MehVahdJukaar** [comment]
there are no versions marked for 1.20.4

**Comment by vico93** [comment]
> there are no versions marked for 1.20.4

Er... and an update for 1.20.4 is on the plans? I really miss this mod...

**Comment by MehVahdJukaar** [comment]
I don't have any immediate plans to update. Ive already update quite some of my other mods to 1.20.4 and they barely got any downloads meaning very few are on that version so not really worth it now
