### ISSUE TITLE
Ghosts of pins [1.20.1]

### ISSUE THREAD

**Issue by TwelveYO21** [MehVahdJukaar/mapatlases-neoforge#83]
Pins that I have not set up appear and sometimes disappear on the minimap.
I think this is, I think, a pin I created with the save data of a previously deleted world with the same name.
Is there a garbage file left behind?

Map atlases : 1.20-2.7.13 / Moonlight : 1.20-2.8.8.84

**Comment by MehVahdJukaar** [comment]
Yes save data is stored in a folder with same name as the world. In your case it would indeed keep them. I need to delete them when you delete a world

**Comment by TwelveYO21** [comment]
So I have to delete the file (nbt) in order to get clear of the pin ghosts?
I have a lot of pins that I have officially set up in my new world, and I don't want to delete them...

**Comment by MehVahdJukaar** [comment]
yeah. they shouldnt be ghost pins though so you could also just delete them manually ingame

**Comment by TwelveYO21** [comment]
No good. The ghost pin has no tabs, so in-game delete operation is not possible.

**Comment by MehVahdJukaar** [comment]
thats weird. so they show on maps but are not on a tab? can you send me your pins file? Should probably make that save in json instead, nbt is harder to read

**Comment by MehVahdJukaar** [comment]
Data will now be erased upon clicking dele world
