### ISSUE TITLE
[Fabric][1.20.01] Entity Lag when map is in Hotbar, Atlasslot or Handslot

### ISSUE THREAD

**Issue by Sharkxx** [MehVahdJukaar/mapatlases-neoforge#84]
When usingt the Atlas entitys like opening chests or mobs in general start to lag. When the Atlas is put back into the inventory that isn't the Hotbar, Atlasslot or Handslot the lag goes away.

Current modlist:
animatica-0.6+1.20.jar
archers-1.0.7+1.20.1.jar
architectury-9.1.12-fabric.jar
azurelibarmor-fabric-1.20.1-2.0.3.jar
bettercombat-fabric-1.8.3+1.20.1.jar
cardinal-components-api-5.2.2.jar
cloth-config-11.1.118-fabric.jar
cloth-config-11.1.118-forge.jar
cupboard-fabric-1.20.1-2.2.jar
dungeons-and-taverns-3.0.3 [Fabric].jar
eating-animation-1.20+1.9.5.jar
entityculling-fabric-1.6.2-mc1.20.1.jar
entity_model_features_fabric_1.20.1-1.2.3.jar
entity_texture_features_fabric_1.20.1-5.2.1.jar
fabric-api-0.91.0+1.20.1.jar
farmers-delight-fabric-mc1.20.1-1.4.2.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
friendsandfoes-fabric-mc1.20.1-2.0.7.jar
IllagerInvasion-v8.0.4-1.20.1-Fabric.jar
indium-1.0.27+mc1.20.1.jar
iris-mc1.20.1-1.6.11.jar
jei-1.20.1-fabric-15.2.0.27.jar
JustEnoughResources-Fabric-1.20.1-1.4.0.247.jar
lootintegrations-fabric-1.20.1-3.4.jar
map_atlases-1.20-2.7.15-fabric.jar
mcda-5.0.1.jar
mcde-1.5.6-1.20.jar
mcdw-8.1.0.jar
modmenu-7.2.2.jar
mods.txt
moonlight-1.20-2.9.3-fabric.jar
paladins-1.0.5+1.20.1.jar
particle-rain-2.0.8.jar
player-animation-lib-fabric-1.0.2-rc1+1.20.jar
projectile_damage-fabric-3.2.2+1.20.1.jar
PuzzlesLib-v8.1.14-1.20.1-Fabric.jar
replaymod-1.20.1-2.6.13.jar
runes-fabric-0.9.11+1.20.1.jar
simplyswords-fabric-1.51.5-1.20.1.jar
sodium-fabric-mc1.20.1-0.5.3.jar
spell_engine-0.12.5+1.20.1.jar
spell_power-fabric-0.9.19+1.20.1.jar
structureessentials-fabric-1.20.1-3.2.jar
supplementaries-1.20-2.7.30-fabric.jar
trade-cycling-fabric-1.20.1-1.0.7.jar
travelers-backpack-1.20.1-9.1.9.jar
trinkets-3.7.1.jar
visuality-0.7.1+1.20.jar
wizards-1.0.5+1.20.1.jar
yet-another-config-lib-fabric-3.2.1+1.20.jar
youre-in-grave-danger-2.0.0-beta.7.jar
YungsApi-1.20-Fabric-4.0.2.jar
YungsBetterDungeons-1.20-Fabric-4.0.3.jar
YungsBetterMineshafts-1.20-Fabric-4.0.4.jar
YungsBetterNetherFortresses-1.20-Fabric-2.0.5.jar
YungsBetterOceanMonuments-1.20-Fabric-3.0.4.jar
YungsBetterStrongholds-1.20-Fabric-4.0.3.jar

![2024-01-28_11 08 08](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/5181947/ead8a8e0-f069-4e21-b0b8-2a54551c5e34)

F3 Screenshot while holding the map, not sure if this helps with anything.

**Comment by MehVahdJukaar** [comment]
So basically when it shows the minimap you loose FPS. That's normal as there's a lot more to render. However shouldn't be that noticeable. Install immediately fast for faster rendering

**Comment by Sharkxx** [comment]
No my fps are the same, its only entitys that start to go from fluid to laggy. The game itself stays stable.

**Comment by Sharkxx** [comment]
Not quite the best video but this should do the trick: https://www.youtube.com/watch?v=B0PfCU7LskY

**Comment by MehVahdJukaar** [comment]
Then it's tick lag. Send a spark report with same test condition, one with the atlas active and one without

**Comment by Sharkxx** [comment]
https://spark.lucko.me/1jP9dHJybX Without
https://spark.lucko.me/fTe7vvgssN With Map in Hotbar

[sparkprofiles_atlaslag.zip](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/14076855/sparkprofiles_atlaslag.zip)

**Comment by MehVahdJukaar** [comment]
thats very weird. game taking a stupid long time to just get blocks
Are you using a high scale map with markers that are far away?
try new version

**Comment by Sharkxx** [comment]
Using the newset Version (1.20-2.7.18 fabric) fixed the issue.
