### ISSUE TITLE
[1.19.2 5.6.8]  Named Banner objects explode after you zoom out (see video)

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/mapatlases-neoforge#85]
https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/50085439/cd3310ed-d430-4f7c-aed0-1235201764b6

**Comment by MehVahdJukaar** [comment]
yeah banner stuff in 1.19 is beyond broken. i guess ill have to painstakingly backport again and theres so much of that

**Comment by thelegitdolt** [comment]
Fixed in 6.0.2 <3

**Comment by thelegitdolt** [comment]
thank you mehvahdjukaar

**Comment by MehVahdJukaar** [comment]
😁
