### ISSUE TITLE
[1.19.2 6.0.0] Client crashes when right clicking the atlas

### ISSUE THREAD

**Issue by AlbusRex** [MehVahdJukaar/mapatlases-neoforge#86]
When right cliking an atlas, client crashes instantly.
Unable to pinpoint root cause besides probable issue regarding atlas failing to fetch stored data according to the crash log.
See attached crash log for further details.
[crash-2024-02-04_16.22.20-client.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/14157323/crash-2024-02-04_16.22.20-client.txt)

**Comment by Vandorsolyom** [comment]
Same issue here!
[crash-2024-02-04_17.16.30-client.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/14157493/crash-2024-02-04_17.16.30-client.txt)

**Comment by AlbusRex** [comment]
Version 6.0.1 persists the issue.
Crash happened when right clicked a newly created atlas.
[crash-2024-02-05_17.37.28-client.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/14168577/crash-2024-02-05_17.37.28-client.txt)

**Comment by AlbusRex** [comment]
Version 6.0.2 persists the issue
Same as last crash.
I has been noticed that the crash triggers when right clicking against any block, r-clicking air opens the atlas GUI.
[crash-2024-02-06_00.14.22-client.txt](https://github.com/MehVahdJukaar/mapatlases-neoforge/files/14172792/crash-2024-02-06_00.14.22-client.txt)

**Comment by AlbusRex** [comment]
The latter file for version 6.0.2 fixes the issue.
Map opens, markers are added and all relevant keybinds seem to work now.
