### ISSUE TITLE
[1.19.2 6.0.2] Can no longer drag atlas

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/mapatlases-neoforge#88]
While in the atlas screen, it is now impossible to move the maps around by dragging.

**Comment by thelegitdolt** [comment]
https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/50085439/010de583-a71a-418b-9e34-024f58828820

i am clicking my mouse and trying to drag the map around, but it's not working lol

**Comment by thelegitdolt** [comment]
this was fixed in 6.0.4!! Thank you Meh Man!

**Comment by MehVahdJukaar** [comment]
Nice, no problem!
