### ISSUE TITLE
Twilight forest magic maps crash player on render when Map atlases is installed

### ISSUE THREAD

**Issue by LeoBeliik** [MehVahdJukaar/mapatlases-neoforge#93]
Forge 47.2.0
Map Atlases 1.20 - 2.7.18
Twilight Forest 1.20.1 - 4.3.2145
Crashlog https://mclo.gs/Sblwed2

Crafting a magic map and holding it in hand will perma kick the player out of the server, **this only happens** when map atlases is installed.

Also reported to Twilight Forest: https://github.com/TeamTwilight/twilightforest/issues/1990

**Comment by LeoBeliik** [comment]
I'm quite sure this was already fixed, no @MehVahdJukaar?

**Comment by MehVahdJukaar** [comment]
definitely. map atlas already has builtin integration with twilight maps, they have their own section and icon on  the atlas. Unless something changed recently this should be closed

**Comment by LeoBeliik** [comment]
Then close it my bro :wacko:

**Comment by elifian** [comment]
Unfortunately, this is not fixed on 1.19.2

**Comment by MehVahdJukaar** [comment]
then send the log as this is clearly in contrast with the original post

**Comment by elifian** [comment]
> then send the log as this is clearly in contrast with the original post

[server.log](https://github.com/user-attachments/files/17365758/server.log)

1.19.2 Forge 43.4.2

ModList on the client
<html><body><ul>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/ai-improvements">AI-Improvements</a> [0.5.2
]</li>
	<li><a href="https://aitchummodding.wixsite.com/mymods">Aitchum - Soundtrack In Music Disc</a> [1.0.0]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/alexs-mobs">Alex's Mobs</a> [1.21.1]</li>
	<li><a href="https://github.com/squeek502/AppleSkin">AppleSkin</a> [2.4.2+mc1.19
]</li>
	<li>Architectury [6.6.92]</li>
	<li>Ars Nouveau [3.23.0
]</li>
	<li>AutoRegLib [1.8.2-55
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/be-style-wither">BE Style Wither</a> [1.3.2]</li>
	<li><a href="https://mrcrayfish.com/mods?id=backpacked">Backpacked</a> [2.1.13]</li>
	<li><a href="https://blay09.net/">Balm</a> [4.6.0
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-advancements">Better Advancements</a> [0.2.2.142]</li>
	<li>Better Block Sounds [1.19.2-1.0]</li>
	<li><a href="https://github.com/ZsoltMolnarrr/BetterCombat">Better Combat</a> [1.7.1+1.19]</li>
	<li>Better Third Person [1.9.0
]</li>
	<li><a href="https://modrinth.com/mod/betterf3">BetterF3</a> [4.0.1]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/big-brain/">Big Brain</a> [1.19.2-1.6.7
]</li>
	<li><a href="https://mcreator.net">BigDan's Music Discs</a> [3.0.0]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/bookshelf">Bookshelf</a> [16.3.20]</li>
	<li><a href="https://botaniamod.net">Botania</a> [1.19.2-440.2-FORGE
]</li>
	<li><a href="https://github.com/TheIllusiveC4/Caelus">Caelus API</a> [1.19.2-3.0.0.6]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/canary">Canary</a> [0.3.3]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/chunk-loaders">Chunk Loaders</a> [1.2.8a]</li>
	<li><a href="https://github.com/Alex-the-666/Citadel">Citadel</a> [2.1.4]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge/">Cloth Config v8 API</a> [8.3.134]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/cloud-storage">Cloud Storage</a> [1.3.4]</li>
	<li><a href="https://mrcrayfish.com/mods?id=configured">Configured</a> [2.1.1]</li>
	<li><a href="https://github.com/CorgiTaco/CorgiLib">CorgiLib</a> [1.0.0.34
]</li>
	<li><a href="https://github.com/zlainsama/CosmeticArmorReworked">CosmeticArmorReworked</a> [1.19.2-v1a
]</li>
	<li><a href="https://minecraft.curseforge.com/projects/crafttweaker">CraftTweaker</a> [10.1.54
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/crafting-automat">Crafting Automat</a> [1.2.3]</li>
	<li><a href="https://modrinth.com/mod/craterlib">CraterLib</a> [2.1.0+hotfix.1]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/create">Create</a> [0.5.1.h
]</li>
	<li><a href="https://github.com/pyzpre/Create-Bicycles-Bitterballen">Create Bitterballen</a> [0.0.86]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-compact-exp">Create Compact Exp (by NoCube)</a> [1.0.4]</li>
	<li>Create Enchantment Industry [1.2.9.e
]</li>
	<li>Create Sifter [1.19.2-1.8.1.e-44
]</li>
	<li>Create Utilities [0.3.0+1.19.2
]</li>
	<li>Create: Central Kitchen [1.3.11.c
]</li>
	<li><a href="https://github.com/copycats-plus/copycats">Create: Copycats+</a> [1.3.8+mc.1.19.2-forge]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-gravity">Create: Gravity</a> [1.2.0]</li>
	<li>Create: New Beginnings [0.1.0-1.19.2]</li>
	<li><a href="https://www.curseforge.com/members/smartstreamlabs_studios/projects">Create: Pillagers Arise</a> [113.23.]</li>
	<li>Create: The Factory Must Grow [0.6.0c]</li>
	<li>CreateTweaker [3.0.0.7
]</li>
	<li>Cupboard utilities [1.19.2-2.6
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/curios">Curios API</a> [1.19.2-5.1.6.3
]</li>
	<li>Custom Starter Gear [2.0.3]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/dark-paintings">DarkPaintings</a> [13.1.5]</li>
	<li><a href="https://github.com/RedLime/DetailArmorBar/tree/1.19-forge">Detail Armor Bar</a> [2.6.4+1.19.2-forge
]</li>
	<li>Dimensional Dungeons [179
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/dimensional-paintings">Dimensional Paintings</a> [1.4.1
]</li>
	<li>Dont Drop Your Compass [1.19.2-1.0]</li>
	<li>Drippy Loading Screen [3.0.1]</li>
	<li>Dynamic Music [2.3.1+1.19.2]</li>
	<li>Embeddium [0.3.18.1+mc1.19.2]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/embeddiumplus">Embeddium++</a> [1.2.13]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions">EnchantmentDescriptions</a> [13.0.14]</li>
	<li>Ender Trigon [1.0]</li>
	<li>EngravingTable [0.0.1]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy">Enigmatic Legacy</a> [2.26.5]</li>
	<li><a href="https://github.com/CorgiTaco/No-Client-Side-Entity-Collision-Checks">Entity Collision FPS Fix</a> [2.0.0.0
]</li>
	<li>Entity Model Features [2.0.2]</li>
	<li>Entity Texture Features [6.0.1]</li>
	<li>EntityCulling [1.6.1]</li>
	<li>Experimental Settings Disabler [1.0]</li>
	<li><a href="https://github.com/MattCzyr/ExplorersCompass">Explorer's Compass</a> [1.19.2-1.3.0-forge
]</li>
	<li><a href="https://github.com/gigaherz/EyesInTheDarkness">Eyes in the Darkness</a> [1.3.10
]</li>
	<li>FTB Dripper [1902.1.0-build.1]</li>
	<li>FTB Library [1902.4.1-build.236]</li>
	<li>FTB Quests [1902.5.9-build.399]</li>
	<li>FTB Teams [1902.2.14-build.123]</li>
	<li>FTB XMod Compat [1.2.4]</li>
	<li><a href="https://github.com/bigenergy/ftb-quests-optimizer">FTBQuestsOptimizer</a> [1.2.1-1.19.2]</li>
	<li>FancyMenu [3.2.3]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/fancyvideo-api">FancyVideo API</a> [2.0.1]</li>
	<li><a href="https://www.apexstudios.dev/fantasys-furniture">Fantasy's Furniture</a> [6.7.0
]</li>
	<li><a href="https://github.com/vectorwing/FarmersDelight">Farmer's Delight</a> [1.19.2-1.2.4]</li>
	<li><a href="https://minecraft.curseforge.com/projects/fast-leaf-decay">FastLeafDecay</a> [30
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/fastload">Fastload-Reforged</a> [3.4.0]</li>
	<li>Ferrite Core [5.0.3
]</li>
	<li>Fog Looks Good Now [1.1.1]</li>
	<li>Forbidden &amp; Arcanus [1.19.2-2.1.5
]</li>
	<li><a href="http://geckolib.com/">GeckoLib</a> [3.1.40
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/genshin-instruments">Genshin Instruments</a> [4.0.2]</li>
	<li>Global Packs [1.14.5_forge
]</li>
	<li>Health Overlay [7.2.1]</li>
	<li>Hexerei [0.3.3.1
]</li>
	<li>Hookshot [1.19.2-1.0]</li>
	<li><a href="https://anthonyhilyard.com/">Iceberg</a> [1.1.4
]</li>
	<li><a href="https://illuminations.uuid.gg/">Illuminations</a> [1.19.2-1.10.9.20]</li>
	<li>ImmediatelyFast [1.2.21+1.19.2]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/ImmersiveMelodies">Immersive Melodies</a> [0.1.2+1.19.2]</li>
	<li><a href="http://github.com/McJtyMods/InControl/">InControl</a> [1.19-7.1.17
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/integrated_api">Integrated API</a> [1.2.7+1.19.2
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/idas">Integrated Dungeons and Structures</a> [1.7.6+1.19.2
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/inventory-crafter">Inventory Crafter</a> [1.1.3
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks">Iron's Spells 'n Spellbooks</a> [1.19.2-2.2.2]</li>
	<li>Item Filters [1902.2.9-build.51]</li>
	<li>JTDItemsInStructure [0.1]</li>
	<li><a href="https://minecraft.curseforge.com/projects/jade">Jade</a> [8.9.2
]</li>
	<li><a href="https://vk.com/trankler_3000">JtD Simple Utilities</a> [1.2.4.3]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/jumbo-furnace">Jumbo Furnace</a> [1.19.2-3.0.0.0
]</li>
	<li><a href="https://www.curseforge.com/projects/238222">Just Enough Items</a> [11.8.1.1033]</li>
	<li>Konkrete [1.8.0]</li>
	<li><a href="https://modrinth.com/mod/ksyxis">Ksyxis</a> [1.1
]</li>
	<li><a href="https://modrinth.com/mod/umyGl7zF">KubeJS</a> [1902.6.2-build.73]</li>
	<li>KubeJSDelight [1.1.2
]</li>
	<li><a href="https://anthonyhilyard.com/">Legendary Tooltips</a> [1.4.0
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/leons-minecraft-dungeons-paintings-mod/download/5241901">Leon's Dungeons Paintings</a> [2.0.0]</li>
	<li>Lightspeed [1.19.2-1.1.0
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/loot-beams">LootBeams</a> [1.0]</li>
	<li><a href="https://minecraft.curseforge.com/projects/lootr">Lootr</a> [0.4.28.73]</li>
	<li>Map Atlases [1.19-6.0.4]</li>
	<li>Melody [1.0.1]</li>
	<li>Memory Leak Fix [1.0.0]</li>
	<li>MmmMmmMmmmmm [1.19.2-1.7.1]</li>
	<li>Moonlight Library [1.19.2-2.3.7]</li>
	<li>Moons Cosmetics [1.19.2-0.2.0]</li>
	<li>More Dragon Eggs [3.2
]</li>
	<li><a href="https://minecraft.curseforge.com/projects/mouse-tweaks">Mouse Tweaks</a> [2.23
]</li>
	<li>Music Manager [1.19.2-1.2.17
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/music-triggers">Music Triggers</a> [1.19.2-6.3.1]</li>
	<li><a href="https://github.com/MattCzyr/NaturesCompass">Nature's Compass</a> [1.19.2-1.10.0-forge
]</li>
	<li><a href="https://modrinth.com/mod/not-enough-animations">NotEnoughAnimations</a> [1.7.6]</li>
	<li>Oculus [1.6.9]</li>
	<li><a href="https://oh-the-biomes-youll-go.fandom.com/wiki/Oh_The_Biomes_You%27ll_Go_Wiki">Oh The Biomes You'll Go</a> [2.0.1.6
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/parcool">ParCool!</a> [1.19.2-3.3.0.1-R
]</li>
	<li>Patchouli [1.19.2-77
]</li>
	<li>Player Animator [1.0.2]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/pluto">Pluto</a> [0.0.9
]</li>
	<li>Polymorph [0.46.6+1.19.2]</li>
	<li>PonderJS [1.2.0]</li>
	<li><a href="https://github.com/Fuzss/portablehole">Portable Hole</a> [4.0.0]</li>
	<li><a href="https://anthonyhilyard.com/">Prism</a> [1.0.2]</li>
	<li><a href="https://github.com/Fuzss/puzzleslib">Puzzles Lib</a> [4.4.3]</li>
	<li>Quark [3.4-418
]</li>
	<li>Quark Oddities [1.18]</li>
	<li>REI Plugin Compatibilities [9.0.90]</li>
	<li>Radon [0.8.2]</li>
	<li>Random World Name [2.3]</li>
	<li>Raw's Visual Keybinder [1.19.2 - 0.1.5
]</li>
	<li>Recall [1.3.1
]</li>
	<li>Rhino [1902.2.3-build.284]</li>
	<li>Roughly Enough Items (REI) [9.2.779]</li>
	<li>Roughly Enough Resources [2.6.1]</li>
	<li>Rubidium Dynamic Lights [1.19.2_v1.4.0
]</li>
	<li><a href="https://modrinth.com/mod/sanity-descent-into-madness">Sanity: Descent Into Madness</a> [1.1.0
]</li>
	<li><a href="https://legacy.curseforge.com/minecraft/mc-mods/saturn">Saturn</a> [0.1.4]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/simple-discord-rpc/">Simple RPC</a> [3.3.2]</li>
	<li><a href="https://modrinth.com/mod/9eGKb6K1">Simple Voice Chat</a> [1.19.2-2.5.23]</li>
	<li>Simply Swords [1.47.0-1.19.2]</li>
	<li>SmartBrainLib [1.9]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded">Smooth Boot (Reloaded)</a> [0.0.4]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered">Sound Physics Remastered</a> [1.19.2-1.4.5]</li>
	<li><a href="https://curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition">Spice of Life: Carrot Edition</a> [1.19.2-1.14.0
]</li>
	<li>Spirit [2.2.7]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/starlight-forge">Starlight</a> [1.1.1+forge.a3aea74]</li>
	<li><a href="https://minecraft.curseforge.com/projects/storagedrawers">Storage Drawers</a> [11.4.1]</li>
	<li><a href="https://moddinglegacy.com/">Structure Gel API</a> [2.7.3
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib">SuperMartijn642's Config Library</a> [1.1.8]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib">SuperMartijn642's Core Lib</a> [1.1.17+a]</li>
	<li>Supplementaries [1.19.2-2.4.20]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/terrablender">TerraBlender</a> [2.0.1.136
]</li>
	<li><a href="https://github.com/ThinkingStudios/textrues-embeddium-options">TexTrue's Embeddium Options</a> [0.1.1+mc1.19.2]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/the-impossible-library">The Impossible Library</a> [1.19.2-0.3.0]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest">The Twilight Forest</a> [4.2.1518
]</li>
	<li>The Undergarden [0.8.3
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/tips">Tips</a> [8.0.27]</li>
	<li><a href="https://minecraft.curseforge.com/projects/totemic">Totemic</a> [1.19.2-0.12.13
]</li>
	<li>Twilight Tweaks [1.0]</li>
	<li><a href="https://mcreator.net">Tyafi</a> [1.0.0]</li>
	<li>UltimateSpawn [1.2.0]</li>
	<li><a href="https://www.curseforge.com/members/nocubeyt/projects">Undergarden Delight</a> [1.0.0]</li>
	<li><a href="https://mcreator.net">Unusual Meme Shoes</a> [0.0.2]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/valhelsia-core">Valhelsia Core</a> [1.19.2-0.5.0
]</li>
	<li><a href="https://github.com/Fuzss/visualworkbench">Visual Workbench</a> [4.2.4]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/visuality-forge">Visuality: Reforged</a> [2.0.2]</li>
	<li><a href="https://blay09.net/mods/waystones">Waystones</a> [11.4.2
]</li>
	<li>What Are You Voting For? [1.0
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-api">YUNG's API</a> [1.19.2-Forge-3.8.10
]</li>
	<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island">YUNG's Better End Island</a> [1.19.2-Forge-1.0]</li>
	<li>biomemusic mod [1.19.2-2.2
]</li>
	<li>e4mc [5.2.1]</li>
	<li>eeriemusic mod [1.19.2-1.4
]</li>
	<li>forbidden_addon [1.19.2-1.0.0]</li>
	<li>sdmcrtplus [1.19.2-V1.7]</li>
	<li>steve_dweller [1.7.0]</li>
	<li>饰品望远镜 [1.7.2]</li>
</ul></body></html>
